@echo off
echo Creating Expo directories...
mkdir "C:\Users\jnoor\.expo" 2>nul
echo Creating schema-cache directory...
mkdir "C:\Users\jnoor\.expo\schema-cache" 2>nul
echo Creating codesigning directory...
mkdir "C:\Users\jnoor\.expo\codesigning" 2>nul
echo Directories created successfully!