@echo off
cd /d "N:\Github-Repo\glowverse app\Glowverse-app\frontend"
echo Starting Expo development server...
echo This will generate a QR code for Expo Go app...
node_modules\.bin\expo start --tunnel